plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    maven { url "https://maven.uku3lig.net/releases/" }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"ctn" {
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/client/resources/ctn.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // ukulib
    modApi("net.uku3lig:ukulib:${project.ukulib_version}")
}

processClientResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
	}
}